codingkatty/mathpylearn

challenge.html
index.html
learn.html
script.js
styles.css

Description:
This pull request includes comprehensive enhancements across the Home, Challenge, and Learn pages of the Math 4 Python application. The following updates have been made:
1.	Home Page Enhancements:
•	Updated layout for better visual hierarchy and user engagement.
•	Added sections highlighting key features and benefits of the platform.
•	Included call-to-action buttons to guide users towards learning and challenges.
2.	Challenge Page Improvements:
•	Enhanced the styling and descriptions for various coding challenges to provide users with better context and motivation.
•	Improved navigation and accessibility, ensuring users can easily find and engage with challenges.
3.	Learn Page Enhancements:
•	Refined the user interface to make it more visually appealing and user-friendly.
• …

Enhance Home, Challenge, and Learn Pages with Improved UI and Features

---

script.js

Fixes #2  I have added the comments in learning of hello world and variable

 Fixes: #2 adds comments to hello world and variables learning

---

index.html
styles.css

Fixed the navbar replication of buttons, and also added mobile responsiveness for the same.

fixed the replication of navbar buttons

---

learn.html
script.js

- added proper logic to display output + with error handling
- converted a div -> text-area for proper output
closes #14

Displays correct output

---

README.md

This PR addresses and Fixes #5 by refining the README for better clarity, structure, and contributor engagement. Key changes include:
- **Reorganized content** to provide a clearer flow, improving readability and understanding of the project’s purpose.
- **Enhanced feature descriptions** with more detailed explanations of how each feature benefits the users.
- **Added contribution guidelines** to outline how users can get involved by creating lessons, designing challenges, fixing bugs, and proposing features.
Additionally, as part of **Hacktoberfest**, please add the **Hacktoberfest** labels to this PR.
This update significantly improves the overall appeal and usability of the README, making it more engaging for the community and encouraging contributions.
---

Enhanced Math4Python README for Improved Clarity and Engagement — Hacktoberfest

---

challenge.html
index.html
learn.html

1. PROBLEM
While clicking on Learn or Challenge, There was a dupliction of buttons in the Navbar as mentioned in the below image:-
SOLUTION
I have commented out the additional navbar links. Now it is working fine. I have tested also.
2. PROBLEM
While hovering on the theme-toggle button we were getting an aero pointer.
SOLUTION
Now there is a cursor pointer which enchances the user experience

Updated the UI

---

styles.css

---
This PR focuses on improving the visual aesthetics of the Math 4 Python website and fixes #6  while ensuring that all existing functionalities remain intact. The following updates were made:
1. **Improved Color Schemes:** 
- Adjusted background and text colors for various elements to enhance visibility and contrast in both dark and light modes. 
- Ensured that all text remains readable against its background, particularly for headings, feature boxes, and challenge descriptions.
2. **Box Design Enhancements:**
- Created visually appealing boxes for features and challenges that adapt to dark and light themes. 
- The feature boxes now have rounded corners and shadows for a more modern look.
3. **No Functional Changes:**
- All core functionalities of the website, including the code editor …

Enhance Aesthetic and User Experience [Hacktoberfest] 

---

script.js
styles.css

This pull request includes updates to enhance the layout and user experience related to the theme toggle button.
- **script.js**: Added titles to the theme toggle button to indicate the current action (e.g., "Switch to Dark Mode" or "Switch to Light Mode"), making it clearer for users what will happen when they click the button.
- **styles.css**: Modified the `.theme-toggle-wrapper` class with the following changes:
- Set `margin-left: auto` and `display: flex` to align the button appropriately.
- Aligned items centrally using `align-items: center`.
- Added padding to the right for improved spacing.
- Adjusted the `transform` property for a more polished position.
These adjustments ensure the button is now positioned to the extreme left before the logo, enhancing its visibility and …

Improve Toggle Theme Button Position and Add Hover Text [Hacktoberfest]

---

challenge.html
script.js

I have added mpore Challenge to enhance this site.And so user get more practise.
Hope u like it.

Added More Challenges.

---

challenge.html
faq.html
index.html
learn.html
script.js
styles.css

Fixed Light/dark mode resets whilen changing page

Fixed Light/dark mode resets whilen changing page

---

challenge.html
learn.html
script.js
styles.css

Feature added progress tracking feature with a visual progress bar for both lessons and challenges. Also added a **"Reset Progress"** button to both the learn and challenge pages. The button will only appear when there's progress to reset. When clicked, it will reset the progress for that specific section **(lessons or challenges)** and update the progress bar accordingly.

Feature added to progress

---

about.html
styles.css

Fix the bug by modifying the CSS.

Fix dark theme bug of About Page

---

learn.html

This PR addresses the feature request to enhance the Python lessons interface by adding headings above the code input and output sections. The new headings will help users, especially beginners, to better understand the purpose of each section and navigate the interface more intuitively.
- Added a heading titled `Code Input` above the left-side box where users type their code.
- Added a heading titled `Output` above the right-side box where users see the results of their code execution.
- Improves the user experience by clearly indicating the functionality of both sections.
- Makes the interface more user-friendly and accessible for beginners.
- Verified that the new headings appear correctly above the respective sections.

Add Headings Above Code Input and Output Boxes

---

learn.html
script.js
styles.css

Added Copy and Reset Button.

---

about.css
about.html

I have updated the about section and made is bit impressive by adding cards and made it responsive.
Here is the final look:
and here is the resposiveness of the website:
Have a look at it and let me know! 
Please consider this PR under `hacktoberfest-accepted`.
Issue: #41

UPDATE ABOUT SECTION

---

about.html
challenge.html
faq.html
hamburger_menu.css
index.html
learn.html
script.js

This PR improves the website's responsiveness and introduces a hamburger menu icon on all pages. These changes ensure that the website provides a seamless user experience across various screen sizes and devices.
1. **Responsive Layouts**:
- Updated CSS to enable responsive layouts across the website.
- Utilized media queries to adjust content, font sizes, and layouts for mobile, tablet, and desktop views.
- Made adjustments to padding, margins, and container sizes to enhance usability on smaller screens.
2. **Hamburger Menu Icon**:
- Added a hamburger menu icon that appears on all pages when viewed on smaller screens.
- Implemented a mobile-friendly navigation menu that slides in/out when the hamburger icon is clicked.
- Ensured that the menu works smoothly across different devices and …

Pull Request: Make Website Responsive and Add Hamburger Menu Icon

---

about.html
challenge.html
faq.html
index.html
learn.html
styles.css

i have changed:-
1. changed the position of home,chall,fqaetc in every page linked like home and all
2. i have also given the name 
3. i have fixed its position of name 
4. border to the logo
5. font of the navlinks
6. given Contrasting color to the navbar whilehover and normally to

Modified the Navbar

---

index.html
styles.css

I have changed the UI of the home page

Modified the UI of the home page

---

about.html
challenge.html
faq.html
index.html
learn.html
styles.css

i have added footer containing:-
1.contact us 
2.quick links 
3.can also follow us 
4.use of site

Added footer

---

learn.html
script.js

Two new lessons are added. Lists and Tuples

List and Tuples lessons added

---

feedback.css
feedback.html
feedback.js
index.html

Fixes #45  closed.Simple Minimal Feedback Form has been added with some CSS effects, and form validation has been implemented.

feedback form added

---

about.html
challenge.html
faq.html
index.html
learn.html
styles.css

Added the nav to top button in all pages. the button will appear only when the scrolling is started. Please merge my request. Closes issue #56 .

Added nav to top button in all pages

---

index.html
learn.html

I have made the learn section responsive and now is not looking broken. 
this is the look:
Please consider this PR under `hacktoberfest-accepted`.
Issue: #63

UPDATE LEARN SECTION

---

feedback.html
feedback.js

GO BACK BUTTON ADDED

---

about.css
about.html

Fixes #69 
Organised About Section with hover effects and other CSS.

Rectified About Section

---

challenge.html
index.html
styles.css

The challenge section is now propely aligned

properly aligned

---

about.css

Change the color of the paragraph from white to make it visible and match the theme.

Refactor about.css to add color to section paragraphs

---

about.html
challenge.html
faq.html
index.html
learn.html

I have align the FAQs section and made is responsive, now its more impressive.
Also i have made its footer responsive too.
here is the look:
Please consider this under `hacktoberfest-accepted`.
Issue: #72

ALIGN FAQs SECTION

---

about.css
about.html

Before it looked like this:
After:

Align Footer Text

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Hey @codingkatty , as per our discussion in issue #86 , I have added both Contributing.md and Code_of_Conduct.md files in the repository with short, precise and user friendly description. 
I hope it gets merged, 
Best Wishes.

Added    CONTRIBUTING.MD  &  CODE_OF_CONDUCT.MD    files to the repository

---

index.html

Bug Fixed [#88 ]
Please refer to the screenshot to see the change.
BEFORE
AFTER

removed the display mishap

---

styles.css

Fixing Font-Size and Color of Challenge page

---

hamburger_menu.css
learn.html

#99 
plzz see hope u liked it.

btn restyled

---

about.html
styles.css

The texts in the about section is now visible in light and dark mode. Please merge my pull request. 
PS: The text colour is not white for both the modes. In dark mode the colour is a lighter white colour and not pure white. 
Closes issue #94

Text abd background visibility in Dark and Light Mode - Problem Rectified

---

learn.html
script.js

**Description:**
I have added an auto-completion feature to the code editor, enhancing the coding experience by providing real-time suggestions as users type. This functionality helps users write code more efficiently by offering keyword suggestions, reducing errors, and improving productivity.
**Features:**
-Auto-completes keywords, functions, and variables as users type.
-Provides real-time suggestions based on the current context.
-Supports a list of custom keywords specific to the programming language in use.
-Includes commonly used code snippets for quicker code writing.
**Screenshot:**
Fixes issue #75

Added auto-completion feature to code editor .

---

about.css

Background Color About Section

---

styles.css

- Enhanced button styling for better usability
- Reorganized navbar for improved layout and structure
Hi @codingkatty,
I'm thrilled to hear your feedback and I truly hope these updates enhance the user experience! 😊 Everything should now look visually appealing on all devices, so feel free to take a peek and share your thoughts! 🌟
Additionally, when you get a moment, could you please add the “hacktoberfest-accepted” label to this PR and merge it? It would mean a lot! 🙏
Also, should I work on the navbar for other pages as well?

Improved Navbar Buttons and Organized Navigation Structure

---

styles.css

- Adjusted the footer size to improve visual balance with the rest of the page
- Updated the layout for better alignment and responsiveness across different screen sizes
- Optimized padding and margins for a cleaner look
- Minor styling tweaks to enhance overall user experience
Hi @codingkatty,
I'm thrilled to hear your feedback and I truly hope these updates enhance the user experience! 😊 Everything should now look visually appealing on all devices, so feel free to take a peek and share your thoughts! 🌟
Additionally, when you get a moment, could you please add the “hacktoberfest-accepted” label to this PR and merge it? It would mean a lot! 🙏

Updated and resized footer for improved layout and responsiveness

---

learn.html

the copy button is duplicated i removed one

Update learn.html copy button duplication

---

about.html
faq.html

Added `onclick="topFunction()"` to the "Back to Top" button on the FAQ page, which was previously missing. Also removed duplicated CSS code defining the button's style.
Fixes [#113](https://github.com/codingkatty/mathpylearn/issues/113)
The HTML file was run directly using Live Server and tested in a browser.

Fix back to top button

---

learn.html
script.js

Added a new class for Try and Except.

Class: Try & Except

---

about.html
faq.html
learn.html
styles.css

I have changed the UI of footer and made it more impressive to look and responsive and also i have added same footer in all the pages. Have a look at it.
Please consider this PR under `hacktoberfest-accepted`.
NEW UI OF FOOTER:
Issue: #119

Improved Footer Section

---

about.html
challenge.html
faq.html
hamburger_menu.css
index.html
learn.html
script.js
styles.css

Standardized the navigation bar across all pages.
Desktop version:
Mobile version:
Fixes [#114](https://github.com/codingkatty/mathpylearn/issues/114)
The HTML file was run directly using Live Server and tested in a browser.

Standardize navigation bar

---

index.html
styles.css

Images are not aligned properly so i had made changes to it

Image Allignment

---

index.html
newfavicon.svg
pages/about.html
pages/learn.html
scripts/feedback.js
styles/styles.css

This PR [fixes](https://github.com/codingkatty/mathpylearn/issues/130) some minor issues.
Let me know if I should make any other changes.
Requesting a review from @codingkatty

Fix major/minor issues
